# Generated by Django 4.2 on 2023-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookseries_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order_in_series',
            field=models.IntegerField(default=1),
        ),
    ]
