# Generated by Django 4.2 on 2023-04-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_order_in_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'default_related_name': 'books', 'ordering': ['series', 'title']},
        ),
    ]
